<?xml version="1.0" encoding="utf-8"?><Database Name="QLNV1" Class="QLNVDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAB1-MAY11\SQLEXPRESS;Initial Catalog=QLNV1;Integrated Security=True" SettingsObjectName="QLNV.Properties.Settings" SettingsPropertyName="QLNV1ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CHUCVU" Member="CHUCVUs">
    <Type Name="CHUCVU">
      <Column Name="MaChucVu" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenChucVu" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="PhuCap" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="CHUCVU_DSNV" Member="DSNVs" ThisKey="MaChucVu" OtherKey="MaChucVu" Type="DSNV" />
    </Type>
  </Table>
  <Table Name="dbo.DSNV" Member="DSNVs">
    <Type Name="DSNV">
      <Column Name="MaNV" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HoDem" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="Ten" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="GioiTinh" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="MaPhong" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="MaChucVu" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="HeSoLuong" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="SoDienThoai" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="CHUCVU_DSNV" Member="CHUCVU" ThisKey="MaChucVu" OtherKey="MaChucVu" Type="CHUCVU" IsForeignKey="true" />
      <Association Name="PHONGBAN_DSNV" Member="PHONGBAN" ThisKey="MaPhong" OtherKey="MaPhong" Type="PHONGBAN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PHONGBAN" Member="PHONGBANs">
    <Type Name="PHONGBAN">
      <Column Name="MaPhong" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenPhong" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="PHONGBAN_DSNV" Member="DSNVs" ThisKey="MaPhong" OtherKey="MaPhong" Type="DSNV" />
    </Type>
  </Table>
</Database>